import jsonContent from "@/openapi/helpers/json-content";
import jsonContentRequired from "@/openapi/helpers/json-content-required";
import * as HttpStatusCodes from "@/config/http-status-codes";
import { createRoute, z } from "@hono/zod-openapi";
import { modelMessageSchema } from "ai";

const tags = ["Chat"];

export const chat = createRoute({
  tags,
  method: "post",
  path: "/chat",
  request: {
    body: jsonContentRequired(
      z.object({
        messages: z.array(modelMessageSchema),
      }),
      "The chat messages to send to the data assistant"
    ),
  },
  responses: {
    [HttpStatusCodes.OK]: jsonContent(
      z.object({
        messages: z.array(modelMessageSchema),
        data: z.array(z.record(z.string(), z.any())).optional(),
      }),
      "The result of the data query generated by the assistant"
    ),
  },
});

export type ChatRoute = typeof chat;
