CREATE MATERIALIZED VIEW "public"."apartments_by_insee_code_month" AS (select "primary_insee_code", "anneemut", "moismut", count(*)::int as "total_sales", round(coalesce(sum("valeurfonc"), 0)) as "total_price", round(coalesce(avg("valeurfonc"), 0)) as "avg_price", round((coalesce(sum("sbatapt"), 0))::numeric, 1) as "total_area", round((coalesce(avg("sbatapt"), 0))::numeric, 1) as "avg_area", round(sum("valeurfonc") / nullif(sum("sbatapt"), 0)) as "avg_price_m2", coalesce(sum("nblocapt"), 0)::int as "total_apartments", coalesce(sum("nbapt1pp"), 0)::int as "apartment_1_room", coalesce(sum("nbapt2pp"), 0)::int as "apartment_2_room", coalesce(sum("nbapt3pp"), 0)::int as "apartment_3_room", coalesce(sum("nbapt4pp"), 0)::int as "apartment_4_room", coalesce(sum("nbapt5pp"), 0)::int as "apartment_5_room", jsonb_build_array(
        round((percentile_cont(0.1) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.2) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.3) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.4) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.5) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.6) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.7) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.8) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.9) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(1.0) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric)
      ) as "price_m2_deciles", round(min("valeurfonc")) as "min_price", round(max("valeurfonc")) as "max_price", round(percentile_cont(0.5) within group (order by "valeurfonc")) as "median_price", round((percentile_cont(0.5) within group (order by "sbatapt"))::numeric, 1) as "median_area", round(min("valeurfonc" / nullif("sbatapt", 0))) as "min_price_m2", round(max("valeurfonc" / nullif("sbatapt", 0))) as "max_price_m2", round(percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatapt", 0))) as "price_m2_p25", round(percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatapt", 0))) as "price_m2_p75", round((percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatapt", 0))) - (percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatapt", 0)))) as "price_m2_iqr", round(stddev_samp("valeurfonc" / nullif("sbatapt", 0))) as "price_m2_stddev" from "property_sales" where ("property_sales"."libtypbien" in ('UN APPARTEMENT', 'DEUX APPARTEMENTS', 'APPARTEMENT INDETERMINE') and "property_sales"."sbatapt" between '10' and '200' and "property_sales"."valeurfonc" between '1500' and '5000000') group by "property_sales"."primary_insee_code", "property_sales"."anneemut", "property_sales"."moismut");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."apartments_by_insee_code_week" AS (select "primary_insee_code", extract(isoyear from "datemut")::int as "iso_year", extract(week from "datemut")::int as "iso_week", count(*)::int as "total_sales", round(coalesce(sum("valeurfonc"), 0)) as "total_price", round(coalesce(avg("valeurfonc"), 0)) as "avg_price", round((coalesce(sum("sbatapt"), 0))::numeric, 1) as "total_area", round((coalesce(avg("sbatapt"), 0))::numeric, 1) as "avg_area", round(sum("valeurfonc") / nullif(sum("sbatapt"), 0)) as "avg_price_m2", coalesce(sum("nblocapt"), 0)::int as "total_apartments", coalesce(sum("nbapt1pp"), 0)::int as "apartment_1_room", coalesce(sum("nbapt2pp"), 0)::int as "apartment_2_room", coalesce(sum("nbapt3pp"), 0)::int as "apartment_3_room", coalesce(sum("nbapt4pp"), 0)::int as "apartment_4_room", coalesce(sum("nbapt5pp"), 0)::int as "apartment_5_room", jsonb_build_array(
        round((percentile_cont(0.1) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.2) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.3) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.4) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.5) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.6) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.7) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.8) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.9) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(1.0) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric)
      ) as "price_m2_deciles", round(min("valeurfonc")) as "min_price", round(max("valeurfonc")) as "max_price", round(percentile_cont(0.5) within group (order by "valeurfonc")) as "median_price", round((percentile_cont(0.5) within group (order by "sbatapt"))::numeric, 1) as "median_area", round(min("valeurfonc" / nullif("sbatapt", 0))) as "min_price_m2", round(max("valeurfonc" / nullif("sbatapt", 0))) as "max_price_m2", round(percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatapt", 0))) as "price_m2_p25", round(percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatapt", 0))) as "price_m2_p75", round((percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatapt", 0))) - (percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatapt", 0)))) as "price_m2_iqr", round(stddev_samp("valeurfonc" / nullif("sbatapt", 0))) as "price_m2_stddev" from "property_sales" where ("property_sales"."libtypbien" in ('UN APPARTEMENT', 'DEUX APPARTEMENTS', 'APPARTEMENT INDETERMINE') and "property_sales"."sbatapt" between '10' and '200' and "property_sales"."valeurfonc" between '1500' and '5000000') group by "property_sales"."primary_insee_code", extract(isoyear from "property_sales"."datemut")::int, extract(week from "property_sales"."datemut")::int);--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."apartments_by_insee_code_year" AS (select "primary_insee_code", "anneemut", count(*)::int as "total_sales", round(coalesce(sum("valeurfonc"), 0)) as "total_price", round(coalesce(avg("valeurfonc"), 0)) as "avg_price", round((coalesce(sum("sbatapt"), 0))::numeric, 1) as "total_area", round((coalesce(avg("sbatapt"), 0))::numeric, 1) as "avg_area", round(sum("valeurfonc") / nullif(sum("sbatapt"), 0)) as "avg_price_m2", coalesce(sum("nblocapt"), 0)::int as "total_apartments", coalesce(sum("nbapt1pp"), 0)::int as "apartment_1_room", coalesce(sum("nbapt2pp"), 0)::int as "apartment_2_room", coalesce(sum("nbapt3pp"), 0)::int as "apartment_3_room", coalesce(sum("nbapt4pp"), 0)::int as "apartment_4_room", coalesce(sum("nbapt5pp"), 0)::int as "apartment_5_room", jsonb_build_array(
        round((percentile_cont(0.1) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.2) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.3) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.4) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.5) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.6) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.7) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.8) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(0.9) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric),
        round((percentile_cont(1.0) within group (order by "valeurfonc" / nullif("sbatapt", 0)))::numeric)
      ) as "price_m2_deciles", round(min("valeurfonc")) as "min_price", round(max("valeurfonc")) as "max_price", round(percentile_cont(0.5) within group (order by "valeurfonc")) as "median_price", round((percentile_cont(0.5) within group (order by "sbatapt"))::numeric, 1) as "median_area", round(min("valeurfonc" / nullif("sbatapt", 0))) as "min_price_m2", round(max("valeurfonc" / nullif("sbatapt", 0))) as "max_price_m2", round(percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatapt", 0))) as "price_m2_p25", round(percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatapt", 0))) as "price_m2_p75", round((percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatapt", 0))) - (percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatapt", 0)))) as "price_m2_iqr", round(stddev_samp("valeurfonc" / nullif("sbatapt", 0))) as "price_m2_stddev" from "property_sales" where ("property_sales"."libtypbien" in ('UN APPARTEMENT', 'DEUX APPARTEMENTS', 'APPARTEMENT INDETERMINE') and "property_sales"."sbatapt" between '10' and '200' and "property_sales"."valeurfonc" between '1500' and '5000000') group by "property_sales"."primary_insee_code", "property_sales"."anneemut");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."houses_by_insee_code_month" AS (select "primary_insee_code", "anneemut", "moismut", count(*)::int as "total_sales", round(coalesce(sum("valeurfonc"), 0)) as "total_price", round(coalesce(avg("valeurfonc"), 0)) as "avg_price", round((coalesce(sum("sbatmai"), 0))::numeric, 1) as "total_area", round((coalesce(avg("sbatmai"), 0))::numeric, 1) as "avg_area", round(sum("valeurfonc") / nullif(sum("sbatmai"), 0)) as "avg_price_m2", coalesce(sum("nblocmai"), 0)::int as "total_houses", coalesce(sum("nbmai1pp"), 0)::int as "house_1_room", coalesce(sum("nbmai2pp"), 0)::int as "house_2_room", coalesce(sum("nbmai3pp"), 0)::int as "house_3_room", coalesce(sum("nbmai4pp"), 0)::int as "house_4_room", coalesce(sum("nbmai5pp"), 0)::int as "house_5_room", jsonb_build_array(
        round((percentile_cont(0.1) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.2) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.3) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.4) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.5) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.6) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.7) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.8) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.9) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(1.0) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric)
      ) as "price_m2_deciles", round(min("valeurfonc")) as "min_price", round(max("valeurfonc")) as "max_price", round(percentile_cont(0.5) within group (order by "valeurfonc")) as "median_price", round((percentile_cont(0.5) within group (order by "sbatmai"))::numeric, 1) as "median_area", round(min("valeurfonc" / nullif("sbatmai", 0))) as "min_price_m2", round(max("valeurfonc" / nullif("sbatmai", 0))) as "max_price_m2", round(percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatmai", 0))) as "price_m2_p25", round(percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatmai", 0))) as "price_m2_p75", round((percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatmai", 0))) - (percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatmai", 0)))) as "price_m2_iqr", round(stddev_samp("valeurfonc" / nullif("sbatmai", 0))) as "price_m2_stddev" from "property_sales" where ("property_sales"."libtypbien" in ('UNE MAISON', 'DES MAISONS', 'MAISON - INDETERMINEE') and "property_sales"."sbatmai" between '20' and '300' and "property_sales"."valeurfonc" between '1500' and '15000000') group by "property_sales"."primary_insee_code", "property_sales"."anneemut", "property_sales"."moismut");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."houses_by_insee_code_week" AS (select "primary_insee_code", extract(isoyear from "datemut")::int as "iso_year", extract(week from "datemut")::int as "iso_week", count(*)::int as "total_sales", round(coalesce(sum("valeurfonc"), 0)) as "total_price", round(coalesce(avg("valeurfonc"), 0)) as "avg_price", round((coalesce(sum("sbatmai"), 0))::numeric, 1) as "total_area", round((coalesce(avg("sbatmai"), 0))::numeric, 1) as "avg_area", round(sum("valeurfonc") / nullif(sum("sbatmai"), 0)) as "avg_price_m2", coalesce(sum("nblocmai"), 0)::int as "total_houses", coalesce(sum("nbmai1pp"), 0)::int as "house_1_room", coalesce(sum("nbmai2pp"), 0)::int as "house_2_room", coalesce(sum("nbmai3pp"), 0)::int as "house_3_room", coalesce(sum("nbmai4pp"), 0)::int as "house_4_room", coalesce(sum("nbmai5pp"), 0)::int as "house_5_room", jsonb_build_array(
        round((percentile_cont(0.1) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.2) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.3) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.4) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.5) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.6) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.7) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.8) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.9) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(1.0) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric)
      ) as "price_m2_deciles", round(min("valeurfonc")) as "min_price", round(max("valeurfonc")) as "max_price", round(percentile_cont(0.5) within group (order by "valeurfonc")) as "median_price", round((percentile_cont(0.5) within group (order by "sbatmai"))::numeric, 1) as "median_area", round(min("valeurfonc" / nullif("sbatmai", 0))) as "min_price_m2", round(max("valeurfonc" / nullif("sbatmai", 0))) as "max_price_m2", round(percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatmai", 0))) as "price_m2_p25", round(percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatmai", 0))) as "price_m2_p75", round((percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatmai", 0))) - (percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatmai", 0)))) as "price_m2_iqr", round(stddev_samp("valeurfonc" / nullif("sbatmai", 0))) as "price_m2_stddev" from "property_sales" where ("property_sales"."libtypbien" in ('UNE MAISON', 'DES MAISONS', 'MAISON - INDETERMINEE') and "property_sales"."sbatmai" between '20' and '300' and "property_sales"."valeurfonc" between '1500' and '15000000') group by "property_sales"."primary_insee_code", extract(isoyear from "property_sales"."datemut")::int, extract(week from "property_sales"."datemut")::int);--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."houses_by_insee_code_year" AS (select "primary_insee_code", "anneemut", count(*)::int as "total_sales", round(coalesce(sum("valeurfonc"), 0)) as "total_price", round(coalesce(avg("valeurfonc"), 0)) as "avg_price", round((coalesce(sum("sbatmai"), 0))::numeric, 1) as "total_area", round((coalesce(avg("sbatmai"), 0))::numeric, 1) as "avg_area", round(sum("valeurfonc") / nullif(sum("sbatmai"), 0)) as "avg_price_m2", coalesce(sum("nblocmai"), 0)::int as "total_houses", coalesce(sum("nbmai1pp"), 0)::int as "house_1_room", coalesce(sum("nbmai2pp"), 0)::int as "house_2_room", coalesce(sum("nbmai3pp"), 0)::int as "house_3_room", coalesce(sum("nbmai4pp"), 0)::int as "house_4_room", coalesce(sum("nbmai5pp"), 0)::int as "house_5_room", jsonb_build_array(
        round((percentile_cont(0.1) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.2) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.3) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.4) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.5) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.6) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.7) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.8) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(0.9) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric),
        round((percentile_cont(1.0) within group (order by "valeurfonc" / nullif("sbatmai", 0)))::numeric)
      ) as "price_m2_deciles", round(min("valeurfonc")) as "min_price", round(max("valeurfonc")) as "max_price", round(percentile_cont(0.5) within group (order by "valeurfonc")) as "median_price", round((percentile_cont(0.5) within group (order by "sbatmai"))::numeric, 1) as "median_area", round(min("valeurfonc" / nullif("sbatmai", 0))) as "min_price_m2", round(max("valeurfonc" / nullif("sbatmai", 0))) as "max_price_m2", round(percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatmai", 0))) as "price_m2_p25", round(percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatmai", 0))) as "price_m2_p75", round((percentile_cont(0.75) within group (order by "valeurfonc" / nullif("sbatmai", 0))) - (percentile_cont(0.25) within group (order by "valeurfonc" / nullif("sbatmai", 0)))) as "price_m2_iqr", round(stddev_samp("valeurfonc" / nullif("sbatmai", 0))) as "price_m2_stddev" from "property_sales" where ("property_sales"."libtypbien" in ('UNE MAISON', 'DES MAISONS', 'MAISON - INDETERMINEE') and "property_sales"."sbatmai" between '20' and '300' and "property_sales"."valeurfonc" between '1500' and '15000000') group by "property_sales"."primary_insee_code", "property_sales"."anneemut");
