DROP MATERIALIZED VIEW IF EXISTS "public"."apartments_by_insee_code_year_deltas" CASCADE;
--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."houses_by_insee_code_year_deltas" CASCADE;
--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."apartments_by_section_year_deltas" CASCADE;
--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."houses_by_section_year_deltas" CASCADE;
--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."apartments_by_insee_code_year_deltas" AS (
  SELECT
    current."insee_code" AS "insee_code",
    current."year" AS "year",
    base."year" AS "base_year",
    -- Core aggregate metrics deltas
    base."total_sales" AS "total_sales_base",
    current."total_sales" AS "total_sales_current",
    current."total_sales" - base."total_sales" AS "total_sales_delta",
    CASE WHEN base."total_sales" IS NULL OR base."total_sales" = 0 THEN NULL ELSE round((100.0 * (current."total_sales" - base."total_sales") / base."total_sales")::numeric, 2)::double precision END AS "total_sales_pct_change",
    base."total_price"::double precision AS "total_price_base",
    current."total_price"::double precision AS "total_price_current",
    (current."total_price"::double precision - base."total_price"::double precision)::double precision AS "total_price_delta",
    CASE WHEN base."total_price" IS NULL OR base."total_price" = 0 THEN NULL ELSE round((100.0 * (current."total_price"::double precision - base."total_price"::double precision) / base."total_price"::double precision)::numeric, 2)::double precision END AS "total_price_pct_change",
    base."avg_price"::double precision AS "avg_price_base",
    current."avg_price"::double precision AS "avg_price_current",
    (current."avg_price"::double precision - base."avg_price"::double precision)::double precision AS "avg_price_delta",
    CASE WHEN base."avg_price" IS NULL OR base."avg_price" = 0 THEN NULL ELSE round((100.0 * (current."avg_price"::double precision - base."avg_price"::double precision) / base."avg_price"::double precision)::numeric, 2)::double precision END AS "avg_price_pct_change",
    base."total_area" AS "total_area_base",
    current."total_area" AS "total_area_current",
    current."total_area" - base."total_area" AS "total_area_delta",
    CASE WHEN base."total_area" IS NULL OR base."total_area" = 0 THEN NULL ELSE round((100.0 * (current."total_area" - base."total_area") / base."total_area")::numeric, 2)::double precision END AS "total_area_pct_change",
    base."avg_area" AS "avg_area_base",
    current."avg_area" AS "avg_area_current",
    current."avg_area" - base."avg_area" AS "avg_area_delta",
    CASE WHEN base."avg_area" IS NULL OR base."avg_area" = 0 THEN NULL ELSE round((100.0 * (current."avg_area" - base."avg_area") / base."avg_area")::numeric, 2)::double precision END AS "avg_area_pct_change",
    base."avg_price_m2"::double precision AS "avg_price_m2_base",
    current."avg_price_m2"::double precision AS "avg_price_m2_current",
    (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision)::double precision AS "avg_price_m2_delta",
    CASE WHEN base."avg_price_m2" IS NULL OR base."avg_price_m2" = 0 THEN NULL ELSE round((100.0 * (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision) / base."avg_price_m2"::double precision)::numeric, 2)::double precision END AS "avg_price_m2_pct_change",
    base."median_price"::double precision AS "median_price_base",
    current."median_price"::double precision AS "median_price_current",
    (current."median_price"::double precision - base."median_price"::double precision)::double precision AS "median_price_delta",
    CASE WHEN base."median_price" IS NULL OR base."median_price" = 0 THEN NULL ELSE round((100.0 * (current."median_price"::double precision - base."median_price"::double precision) / base."median_price"::double precision)::numeric, 2)::double precision END AS "median_price_pct_change",
    base."median_area" AS "median_area_base",
    current."median_area" AS "median_area_current",
    current."median_area" - base."median_area" AS "median_area_delta",
    CASE WHEN base."median_area" IS NULL OR base."median_area" = 0 THEN NULL ELSE round((100.0 * (current."median_area" - base."median_area") / base."median_area")::numeric, 2)::double precision END AS "median_area_pct_change",
    base."price_m2_p25"::double precision AS "price_m2_p25_base",
    current."price_m2_p25"::double precision AS "price_m2_p25_current",
    (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision)::double precision AS "price_m2_p25_delta",
    CASE WHEN base."price_m2_p25" IS NULL OR base."price_m2_p25" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision) / base."price_m2_p25"::double precision)::numeric, 2)::double precision END AS "price_m2_p25_pct_change",
    base."price_m2_p75"::double precision AS "price_m2_p75_base",
    current."price_m2_p75"::double precision AS "price_m2_p75_current",
    (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision)::double precision AS "price_m2_p75_delta",
    CASE WHEN base."price_m2_p75" IS NULL OR base."price_m2_p75" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision) / base."price_m2_p75"::double precision)::numeric, 2)::double precision END AS "price_m2_p75_pct_change",
    base."price_m2_iqr"::double precision AS "price_m2_iqr_base",
    current."price_m2_iqr"::double precision AS "price_m2_iqr_current",
    (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision)::double precision AS "price_m2_iqr_delta",
    CASE WHEN base."price_m2_iqr" IS NULL OR base."price_m2_iqr" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision) / base."price_m2_iqr"::double precision)::numeric, 2)::double precision END AS "price_m2_iqr_pct_change",
    base."price_m2_stddev"::double precision AS "price_m2_stddev_base",
    current."price_m2_stddev"::double precision AS "price_m2_stddev_current",
    (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision)::double precision AS "price_m2_stddev_delta",
    CASE WHEN base."price_m2_stddev" IS NULL OR base."price_m2_stddev" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision) / base."price_m2_stddev"::double precision)::numeric, 2)::double precision END AS "price_m2_stddev_pct_change",
    -- Apartment composition deltas
    base."total_apartments" AS "total_apartments_base",
    current."total_apartments" AS "total_apartments_current",
    current."total_apartments" - base."total_apartments" AS "total_apartments_delta",
    CASE WHEN base."total_apartments" IS NULL OR base."total_apartments" = 0 THEN NULL ELSE round((100.0 * (current."total_apartments" - base."total_apartments") / base."total_apartments")::numeric, 2)::double precision END AS "total_apartments_pct_change",
    base."apartment_1_room" AS "apartment_1_room_base",
    current."apartment_1_room" AS "apartment_1_room_current",
    current."apartment_1_room" - base."apartment_1_room" AS "apartment_1_room_delta",
    CASE WHEN base."apartment_1_room" IS NULL OR base."apartment_1_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_1_room" - base."apartment_1_room") / base."apartment_1_room")::numeric, 2)::double precision END AS "apartment_1_room_pct_change",
    base."apartment_2_room" AS "apartment_2_room_base",
    current."apartment_2_room" AS "apartment_2_room_current",
    current."apartment_2_room" - base."apartment_2_room" AS "apartment_2_room_delta",
    CASE WHEN base."apartment_2_room" IS NULL OR base."apartment_2_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_2_room" - base."apartment_2_room") / base."apartment_2_room")::numeric, 2)::double precision END AS "apartment_2_room_pct_change",
    base."apartment_3_room" AS "apartment_3_room_base",
    current."apartment_3_room" AS "apartment_3_room_current",
    current."apartment_3_room" - base."apartment_3_room" AS "apartment_3_room_delta",
    CASE WHEN base."apartment_3_room" IS NULL OR base."apartment_3_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_3_room" - base."apartment_3_room") / base."apartment_3_room")::numeric, 2)::double precision END AS "apartment_3_room_pct_change",
    base."apartment_4_room" AS "apartment_4_room_base",
    current."apartment_4_room" AS "apartment_4_room_current",
    current."apartment_4_room" - base."apartment_4_room" AS "apartment_4_room_delta",
    CASE WHEN base."apartment_4_room" IS NULL OR base."apartment_4_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_4_room" - base."apartment_4_room") / base."apartment_4_room")::numeric, 2)::double precision END AS "apartment_4_room_pct_change",
    base."apartment_5_room" AS "apartment_5_room_base",
    current."apartment_5_room" AS "apartment_5_room_current",
    current."apartment_5_room" - base."apartment_5_room" AS "apartment_5_room_delta",
    CASE WHEN base."apartment_5_room" IS NULL OR base."apartment_5_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_5_room" - base."apartment_5_room") / base."apartment_5_room")::numeric, 2)::double precision END AS "apartment_5_room_pct_change"
  FROM "apartments_by_insee_code_year" AS current
  INNER JOIN "apartments_by_insee_code_year" AS base
    ON current."insee_code" = base."insee_code"
    AND current."year" = base."year" + 1
);
--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."houses_by_insee_code_year_deltas" AS (
  SELECT
    current."insee_code" AS "insee_code",
    current."year" AS "year",
    base."year" AS "base_year",
    -- Core aggregate metrics deltas
    base."total_sales" AS "total_sales_base",
    current."total_sales" AS "total_sales_current",
    current."total_sales" - base."total_sales" AS "total_sales_delta",
    CASE WHEN base."total_sales" IS NULL OR base."total_sales" = 0 THEN NULL ELSE round((100.0 * (current."total_sales" - base."total_sales") / base."total_sales")::numeric, 2)::double precision END AS "total_sales_pct_change",
    base."total_price"::double precision AS "total_price_base",
    current."total_price"::double precision AS "total_price_current",
    (current."total_price"::double precision - base."total_price"::double precision)::double precision AS "total_price_delta",
    CASE WHEN base."total_price" IS NULL OR base."total_price" = 0 THEN NULL ELSE round((100.0 * (current."total_price"::double precision - base."total_price"::double precision) / base."total_price"::double precision)::numeric, 2)::double precision END AS "total_price_pct_change",
    base."avg_price"::double precision AS "avg_price_base",
    current."avg_price"::double precision AS "avg_price_current",
    (current."avg_price"::double precision - base."avg_price"::double precision)::double precision AS "avg_price_delta",
    CASE WHEN base."avg_price" IS NULL OR base."avg_price" = 0 THEN NULL ELSE round((100.0 * (current."avg_price"::double precision - base."avg_price"::double precision) / base."avg_price"::double precision)::numeric, 2)::double precision END AS "avg_price_pct_change",
    base."total_area" AS "total_area_base",
    current."total_area" AS "total_area_current",
    current."total_area" - base."total_area" AS "total_area_delta",
    CASE WHEN base."total_area" IS NULL OR base."total_area" = 0 THEN NULL ELSE round((100.0 * (current."total_area" - base."total_area") / base."total_area")::numeric, 2)::double precision END AS "total_area_pct_change",
    base."avg_area" AS "avg_area_base",
    current."avg_area" AS "avg_area_current",
    current."avg_area" - base."avg_area" AS "avg_area_delta",
    CASE WHEN base."avg_area" IS NULL OR base."avg_area" = 0 THEN NULL ELSE round((100.0 * (current."avg_area" - base."avg_area") / base."avg_area")::numeric, 2)::double precision END AS "avg_area_pct_change",
    base."avg_price_m2"::double precision AS "avg_price_m2_base",
    current."avg_price_m2"::double precision AS "avg_price_m2_current",
    (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision)::double precision AS "avg_price_m2_delta",
    CASE WHEN base."avg_price_m2" IS NULL OR base."avg_price_m2" = 0 THEN NULL ELSE round((100.0 * (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision) / base."avg_price_m2"::double precision)::numeric, 2)::double precision END AS "avg_price_m2_pct_change",
    base."median_price"::double precision AS "median_price_base",
    current."median_price"::double precision AS "median_price_current",
    (current."median_price"::double precision - base."median_price"::double precision)::double precision AS "median_price_delta",
    CASE WHEN base."median_price" IS NULL OR base."median_price" = 0 THEN NULL ELSE round((100.0 * (current."median_price"::double precision - base."median_price"::double precision) / base."median_price"::double precision)::numeric, 2)::double precision END AS "median_price_pct_change",
    base."median_area" AS "median_area_base",
    current."median_area" AS "median_area_current",
    current."median_area" - base."median_area" AS "median_area_delta",
    CASE WHEN base."median_area" IS NULL OR base."median_area" = 0 THEN NULL ELSE round((100.0 * (current."median_area" - base."median_area") / base."median_area")::numeric, 2)::double precision END AS "median_area_pct_change",
    base."price_m2_p25"::double precision AS "price_m2_p25_base",
    current."price_m2_p25"::double precision AS "price_m2_p25_current",
    (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision)::double precision AS "price_m2_p25_delta",
    CASE WHEN base."price_m2_p25" IS NULL OR base."price_m2_p25" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision) / base."price_m2_p25"::double precision)::numeric, 2)::double precision END AS "price_m2_p25_pct_change",
    base."price_m2_p75"::double precision AS "price_m2_p75_base",
    current."price_m2_p75"::double precision AS "price_m2_p75_current",
    (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision)::double precision AS "price_m2_p75_delta",
    CASE WHEN base."price_m2_p75" IS NULL OR base."price_m2_p75" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision) / base."price_m2_p75"::double precision)::numeric, 2)::double precision END AS "price_m2_p75_pct_change",
    base."price_m2_iqr"::double precision AS "price_m2_iqr_base",
    current."price_m2_iqr"::double precision AS "price_m2_iqr_current",
    (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision)::double precision AS "price_m2_iqr_delta",
    CASE WHEN base."price_m2_iqr" IS NULL OR base."price_m2_iqr" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision) / base."price_m2_iqr"::double precision)::numeric, 2)::double precision END AS "price_m2_iqr_pct_change",
    base."price_m2_stddev"::double precision AS "price_m2_stddev_base",
    current."price_m2_stddev"::double precision AS "price_m2_stddev_current",
    (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision)::double precision AS "price_m2_stddev_delta",
    CASE WHEN base."price_m2_stddev" IS NULL OR base."price_m2_stddev" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision) / base."price_m2_stddev"::double precision)::numeric, 2)::double precision END AS "price_m2_stddev_pct_change",
    -- House composition deltas
    base."total_houses" AS "total_houses_base",
    current."total_houses" AS "total_houses_current",
    current."total_houses" - base."total_houses" AS "total_houses_delta",
    CASE WHEN base."total_houses" IS NULL OR base."total_houses" = 0 THEN NULL ELSE round((100.0 * (current."total_houses" - base."total_houses") / base."total_houses")::numeric, 2)::double precision END AS "total_houses_pct_change",
    base."house_1_room" AS "house_1_room_base",
    current."house_1_room" AS "house_1_room_current",
    current."house_1_room" - base."house_1_room" AS "house_1_room_delta",
    CASE WHEN base."house_1_room" IS NULL OR base."house_1_room" = 0 THEN NULL ELSE round((100.0 * (current."house_1_room" - base."house_1_room") / base."house_1_room")::numeric, 2)::double precision END AS "house_1_room_pct_change",
    base."house_2_room" AS "house_2_room_base",
    current."house_2_room" AS "house_2_room_current",
    current."house_2_room" - base."house_2_room" AS "house_2_room_delta",
    CASE WHEN base."house_2_room" IS NULL OR base."house_2_room" = 0 THEN NULL ELSE round((100.0 * (current."house_2_room" - base."house_2_room") / base."house_2_room")::numeric, 2)::double precision END AS "house_2_room_pct_change",
    base."house_3_room" AS "house_3_room_base",
    current."house_3_room" AS "house_3_room_current",
    current."house_3_room" - base."house_3_room" AS "house_3_room_delta",
    CASE WHEN base."house_3_room" IS NULL OR base."house_3_room" = 0 THEN NULL ELSE round((100.0 * (current."house_3_room" - base."house_3_room") / base."house_3_room")::numeric, 2)::double precision END AS "house_3_room_pct_change",
    base."house_4_room" AS "house_4_room_base",
    current."house_4_room" AS "house_4_room_current",
    current."house_4_room" - base."house_4_room" AS "house_4_room_delta",
    CASE WHEN base."house_4_room" IS NULL OR base."house_4_room" = 0 THEN NULL ELSE round((100.0 * (current."house_4_room" - base."house_4_room") / base."house_4_room")::numeric, 2)::double precision END AS "house_4_room_pct_change",
    base."house_5_room" AS "house_5_room_base",
    current."house_5_room" AS "house_5_room_current",
    current."house_5_room" - base."house_5_room" AS "house_5_room_delta",
    CASE WHEN base."house_5_room" IS NULL OR base."house_5_room" = 0 THEN NULL ELSE round((100.0 * (current."house_5_room" - base."house_5_room") / base."house_5_room")::numeric, 2)::double precision END AS "house_5_room_pct_change"
  FROM "houses_by_insee_code_year" AS current
  INNER JOIN "houses_by_insee_code_year" AS base
    ON current."insee_code" = base."insee_code"
    AND current."year" = base."year" + 1
);
--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."apartments_by_section_year_deltas" AS (
  SELECT
    current."insee_code" AS "insee_code",
    current."section" AS "section",
    current."year" AS "year",
    base."year" AS "base_year",
    -- Core aggregate metrics deltas
    base."total_sales" AS "total_sales_base",
    current."total_sales" AS "total_sales_current",
    current."total_sales" - base."total_sales" AS "total_sales_delta",
    CASE WHEN base."total_sales" IS NULL OR base."total_sales" = 0 THEN NULL ELSE round((100.0 * (current."total_sales" - base."total_sales") / base."total_sales")::numeric, 2)::double precision END AS "total_sales_pct_change",
    base."total_price"::double precision AS "total_price_base",
    current."total_price"::double precision AS "total_price_current",
    (current."total_price"::double precision - base."total_price"::double precision)::double precision AS "total_price_delta",
    CASE WHEN base."total_price" IS NULL OR base."total_price" = 0 THEN NULL ELSE round((100.0 * (current."total_price"::double precision - base."total_price"::double precision) / base."total_price"::double precision)::numeric, 2)::double precision END AS "total_price_pct_change",
    base."avg_price"::double precision AS "avg_price_base",
    current."avg_price"::double precision AS "avg_price_current",
    (current."avg_price"::double precision - base."avg_price"::double precision)::double precision AS "avg_price_delta",
    CASE WHEN base."avg_price" IS NULL OR base."avg_price" = 0 THEN NULL ELSE round((100.0 * (current."avg_price"::double precision - base."avg_price"::double precision) / base."avg_price"::double precision)::numeric, 2)::double precision END AS "avg_price_pct_change",
    base."total_area" AS "total_area_base",
    current."total_area" AS "total_area_current",
    current."total_area" - base."total_area" AS "total_area_delta",
    CASE WHEN base."total_area" IS NULL OR base."total_area" = 0 THEN NULL ELSE round((100.0 * (current."total_area" - base."total_area") / base."total_area")::numeric, 2)::double precision END AS "total_area_pct_change",
    base."avg_area" AS "avg_area_base",
    current."avg_area" AS "avg_area_current",
    current."avg_area" - base."avg_area" AS "avg_area_delta",
    CASE WHEN base."avg_area" IS NULL OR base."avg_area" = 0 THEN NULL ELSE round((100.0 * (current."avg_area" - base."avg_area") / base."avg_area")::numeric, 2)::double precision END AS "avg_area_pct_change",
    base."avg_price_m2"::double precision AS "avg_price_m2_base",
    current."avg_price_m2"::double precision AS "avg_price_m2_current",
    (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision)::double precision AS "avg_price_m2_delta",
    CASE WHEN base."avg_price_m2" IS NULL OR base."avg_price_m2" = 0 THEN NULL ELSE round((100.0 * (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision) / base."avg_price_m2"::double precision)::numeric, 2)::double precision END AS "avg_price_m2_pct_change",
    base."median_price"::double precision AS "median_price_base",
    current."median_price"::double precision AS "median_price_current",
    (current."median_price"::double precision - base."median_price"::double precision)::double precision AS "median_price_delta",
    CASE WHEN base."median_price" IS NULL OR base."median_price" = 0 THEN NULL ELSE round((100.0 * (current."median_price"::double precision - base."median_price"::double precision) / base."median_price"::double precision)::numeric, 2)::double precision END AS "median_price_pct_change",
    base."median_area" AS "median_area_base",
    current."median_area" AS "median_area_current",
    current."median_area" - base."median_area" AS "median_area_delta",
    CASE WHEN base."median_area" IS NULL OR base."median_area" = 0 THEN NULL ELSE round((100.0 * (current."median_area" - base."median_area") / base."median_area")::numeric, 2)::double precision END AS "median_area_pct_change",
    base."price_m2_p25"::double precision AS "price_m2_p25_base",
    current."price_m2_p25"::double precision AS "price_m2_p25_current",
    (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision)::double precision AS "price_m2_p25_delta",
    CASE WHEN base."price_m2_p25" IS NULL OR base."price_m2_p25" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision) / base."price_m2_p25"::double precision)::numeric, 2)::double precision END AS "price_m2_p25_pct_change",
    base."price_m2_p75"::double precision AS "price_m2_p75_base",
    current."price_m2_p75"::double precision AS "price_m2_p75_current",
    (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision)::double precision AS "price_m2_p75_delta",
    CASE WHEN base."price_m2_p75" IS NULL OR base."price_m2_p75" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision) / base."price_m2_p75"::double precision)::numeric, 2)::double precision END AS "price_m2_p75_pct_change",
    base."price_m2_iqr"::double precision AS "price_m2_iqr_base",
    current."price_m2_iqr"::double precision AS "price_m2_iqr_current",
    (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision)::double precision AS "price_m2_iqr_delta",
    CASE WHEN base."price_m2_iqr" IS NULL OR base."price_m2_iqr" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision) / base."price_m2_iqr"::double precision)::numeric, 2)::double precision END AS "price_m2_iqr_pct_change",
    base."price_m2_stddev"::double precision AS "price_m2_stddev_base",
    current."price_m2_stddev"::double precision AS "price_m2_stddev_current",
    (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision)::double precision AS "price_m2_stddev_delta",
    CASE WHEN base."price_m2_stddev" IS NULL OR base."price_m2_stddev" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision) / base."price_m2_stddev"::double precision)::numeric, 2)::double precision END AS "price_m2_stddev_pct_change",
    -- Apartment composition deltas
    base."total_apartments" AS "total_apartments_base",
    current."total_apartments" AS "total_apartments_current",
    current."total_apartments" - base."total_apartments" AS "total_apartments_delta",
    CASE WHEN base."total_apartments" IS NULL OR base."total_apartments" = 0 THEN NULL ELSE round((100.0 * (current."total_apartments" - base."total_apartments") / base."total_apartments")::numeric, 2)::double precision END AS "total_apartments_pct_change",
    base."apartment_1_room" AS "apartment_1_room_base",
    current."apartment_1_room" AS "apartment_1_room_current",
    current."apartment_1_room" - base."apartment_1_room" AS "apartment_1_room_delta",
    CASE WHEN base."apartment_1_room" IS NULL OR base."apartment_1_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_1_room" - base."apartment_1_room") / base."apartment_1_room")::numeric, 2)::double precision END AS "apartment_1_room_pct_change",
    base."apartment_2_room" AS "apartment_2_room_base",
    current."apartment_2_room" AS "apartment_2_room_current",
    current."apartment_2_room" - base."apartment_2_room" AS "apartment_2_room_delta",
    CASE WHEN base."apartment_2_room" IS NULL OR base."apartment_2_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_2_room" - base."apartment_2_room") / base."apartment_2_room")::numeric, 2)::double precision END AS "apartment_2_room_pct_change",
    base."apartment_3_room" AS "apartment_3_room_base",
    current."apartment_3_room" AS "apartment_3_room_current",
    current."apartment_3_room" - base."apartment_3_room" AS "apartment_3_room_delta",
    CASE WHEN base."apartment_3_room" IS NULL OR base."apartment_3_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_3_room" - base."apartment_3_room") / base."apartment_3_room")::numeric, 2)::double precision END AS "apartment_3_room_pct_change",
    base."apartment_4_room" AS "apartment_4_room_base",
    current."apartment_4_room" AS "apartment_4_room_current",
    current."apartment_4_room" - base."apartment_4_room" AS "apartment_4_room_delta",
    CASE WHEN base."apartment_4_room" IS NULL OR base."apartment_4_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_4_room" - base."apartment_4_room") / base."apartment_4_room")::numeric, 2)::double precision END AS "apartment_4_room_pct_change",
    base."apartment_5_room" AS "apartment_5_room_base",
    current."apartment_5_room" AS "apartment_5_room_current",
    current."apartment_5_room" - base."apartment_5_room" AS "apartment_5_room_delta",
    CASE WHEN base."apartment_5_room" IS NULL OR base."apartment_5_room" = 0 THEN NULL ELSE round((100.0 * (current."apartment_5_room" - base."apartment_5_room") / base."apartment_5_room")::numeric, 2)::double precision END AS "apartment_5_room_pct_change"
  FROM "apartments_by_section_year" AS current
  INNER JOIN "apartments_by_section_year" AS base
    ON current."section" = base."section"
    AND current."year" = base."year" + 1
);
--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."houses_by_section_year_deltas" AS (
  SELECT
    current."insee_code" AS "insee_code",
    current."section" AS "section",
    current."year" AS "year",
    base."year" AS "base_year",
    -- Core aggregate metrics deltas
    base."total_sales" AS "total_sales_base",
    current."total_sales" AS "total_sales_current",
    current."total_sales" - base."total_sales" AS "total_sales_delta",
    CASE WHEN base."total_sales" IS NULL OR base."total_sales" = 0 THEN NULL ELSE round((100.0 * (current."total_sales" - base."total_sales") / base."total_sales")::numeric, 2)::double precision END AS "total_sales_pct_change",
    base."total_price"::double precision AS "total_price_base",
    current."total_price"::double precision AS "total_price_current",
    (current."total_price"::double precision - base."total_price"::double precision)::double precision AS "total_price_delta",
    CASE WHEN base."total_price" IS NULL OR base."total_price" = 0 THEN NULL ELSE round((100.0 * (current."total_price"::double precision - base."total_price"::double precision) / base."total_price"::double precision)::numeric, 2)::double precision END AS "total_price_pct_change",
    base."avg_price"::double precision AS "avg_price_base",
    current."avg_price"::double precision AS "avg_price_current",
    (current."avg_price"::double precision - base."avg_price"::double precision)::double precision AS "avg_price_delta",
    CASE WHEN base."avg_price" IS NULL OR base."avg_price" = 0 THEN NULL ELSE round((100.0 * (current."avg_price"::double precision - base."avg_price"::double precision) / base."avg_price"::double precision)::numeric, 2)::double precision END AS "avg_price_pct_change",
    base."total_area" AS "total_area_base",
    current."total_area" AS "total_area_current",
    current."total_area" - base."total_area" AS "total_area_delta",
    CASE WHEN base."total_area" IS NULL OR base."total_area" = 0 THEN NULL ELSE round((100.0 * (current."total_area" - base."total_area") / base."total_area")::numeric, 2)::double precision END AS "total_area_pct_change",
    base."avg_area" AS "avg_area_base",
    current."avg_area" AS "avg_area_current",
    current."avg_area" - base."avg_area" AS "avg_area_delta",
    CASE WHEN base."avg_area" IS NULL OR base."avg_area" = 0 THEN NULL ELSE round((100.0 * (current."avg_area" - base."avg_area") / base."avg_area")::numeric, 2)::double precision END AS "avg_area_pct_change",
    base."avg_price_m2"::double precision AS "avg_price_m2_base",
    current."avg_price_m2"::double precision AS "avg_price_m2_current",
    (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision)::double precision AS "avg_price_m2_delta",
    CASE WHEN base."avg_price_m2" IS NULL OR base."avg_price_m2" = 0 THEN NULL ELSE round((100.0 * (current."avg_price_m2"::double precision - base."avg_price_m2"::double precision) / base."avg_price_m2"::double precision)::numeric, 2)::double precision END AS "avg_price_m2_pct_change",
    base."median_price"::double precision AS "median_price_base",
    current."median_price"::double precision AS "median_price_current",
    (current."median_price"::double precision - base."median_price"::double precision)::double precision AS "median_price_delta",
    CASE WHEN base."median_price" IS NULL OR base."median_price" = 0 THEN NULL ELSE round((100.0 * (current."median_price"::double precision - base."median_price"::double precision) / base."median_price"::double precision)::numeric, 2)::double precision END AS "median_price_pct_change",
    base."median_area" AS "median_area_base",
    current."median_area" AS "median_area_current",
    current."median_area" - base."median_area" AS "median_area_delta",
    CASE WHEN base."median_area" IS NULL OR base."median_area" = 0 THEN NULL ELSE round((100.0 * (current."median_area" - base."median_area") / base."median_area")::numeric, 2)::double precision END AS "median_area_pct_change",
    base."price_m2_p25"::double precision AS "price_m2_p25_base",
    current."price_m2_p25"::double precision AS "price_m2_p25_current",
    (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision)::double precision AS "price_m2_p25_delta",
    CASE WHEN base."price_m2_p25" IS NULL OR base."price_m2_p25" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p25"::double precision - base."price_m2_p25"::double precision) / base."price_m2_p25"::double precision)::numeric, 2)::double precision END AS "price_m2_p25_pct_change",
    base."price_m2_p75"::double precision AS "price_m2_p75_base",
    current."price_m2_p75"::double precision AS "price_m2_p75_current",
    (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision)::double precision AS "price_m2_p75_delta",
    CASE WHEN base."price_m2_p75" IS NULL OR base."price_m2_p75" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_p75"::double precision - base."price_m2_p75"::double precision) / base."price_m2_p75"::double precision)::numeric, 2)::double precision END AS "price_m2_p75_pct_change",
    base."price_m2_iqr"::double precision AS "price_m2_iqr_base",
    current."price_m2_iqr"::double precision AS "price_m2_iqr_current",
    (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision)::double precision AS "price_m2_iqr_delta",
    CASE WHEN base."price_m2_iqr" IS NULL OR base."price_m2_iqr" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_iqr"::double precision - base."price_m2_iqr"::double precision) / base."price_m2_iqr"::double precision)::numeric, 2)::double precision END AS "price_m2_iqr_pct_change",
    base."price_m2_stddev"::double precision AS "price_m2_stddev_base",
    current."price_m2_stddev"::double precision AS "price_m2_stddev_current",
    (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision)::double precision AS "price_m2_stddev_delta",
    CASE WHEN base."price_m2_stddev" IS NULL OR base."price_m2_stddev" = 0 THEN NULL ELSE round((100.0 * (current."price_m2_stddev"::double precision - base."price_m2_stddev"::double precision) / base."price_m2_stddev"::double precision)::numeric, 2)::double precision END AS "price_m2_stddev_pct_change",
    -- House composition deltas
    base."total_houses" AS "total_houses_base",
    current."total_houses" AS "total_houses_current",
    current."total_houses" - base."total_houses" AS "total_houses_delta",
    CASE WHEN base."total_houses" IS NULL OR base."total_houses" = 0 THEN NULL ELSE round((100.0 * (current."total_houses" - base."total_houses") / base."total_houses")::numeric, 2)::double precision END AS "total_houses_pct_change",
    base."house_1_room" AS "house_1_room_base",
    current."house_1_room" AS "house_1_room_current",
    current."house_1_room" - base."house_1_room" AS "house_1_room_delta",
    CASE WHEN base."house_1_room" IS NULL OR base."house_1_room" = 0 THEN NULL ELSE round((100.0 * (current."house_1_room" - base."house_1_room") / base."house_1_room")::numeric, 2)::double precision END AS "house_1_room_pct_change",
    base."house_2_room" AS "house_2_room_base",
    current."house_2_room" AS "house_2_room_current",
    current."house_2_room" - base."house_2_room" AS "house_2_room_delta",
    CASE WHEN base."house_2_room" IS NULL OR base."house_2_room" = 0 THEN NULL ELSE round((100.0 * (current."house_2_room" - base."house_2_room") / base."house_2_room")::numeric, 2)::double precision END AS "house_2_room_pct_change",
    base."house_3_room" AS "house_3_room_base",
    current."house_3_room" AS "house_3_room_current",
    current."house_3_room" - base."house_3_room" AS "house_3_room_delta",
    CASE WHEN base."house_3_room" IS NULL OR base."house_3_room" = 0 THEN NULL ELSE round((100.0 * (current."house_3_room" - base."house_3_room") / base."house_3_room")::numeric, 2)::double precision END AS "house_3_room_pct_change",
    base."house_4_room" AS "house_4_room_base",
    current."house_4_room" AS "house_4_room_current",
    current."house_4_room" - base."house_4_room" AS "house_4_room_delta",
    CASE WHEN base."house_4_room" IS NULL OR base."house_4_room" = 0 THEN NULL ELSE round((100.0 * (current."house_4_room" - base."house_4_room") / base."house_4_room")::numeric, 2)::double precision END AS "house_4_room_pct_change",
    base."house_5_room" AS "house_5_room_base",
    current."house_5_room" AS "house_5_room_current",
    current."house_5_room" - base."house_5_room" AS "house_5_room_delta",
    CASE WHEN base."house_5_room" IS NULL OR base."house_5_room" = 0 THEN NULL ELSE round((100.0 * (current."house_5_room" - base."house_5_room") / base."house_5_room")::numeric, 2)::double precision END AS "house_5_room_pct_change"
  FROM "houses_by_section_year" AS current
  INNER JOIN "houses_by_section_year" AS base
    ON current."section" = base."section"
    AND current."year" = base."year" + 1
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_apts_insee_year_deltas" ON "apartments_by_insee_code_year_deltas" ("insee_code", "year", "base_year");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_houses_insee_year_deltas" ON "houses_by_insee_code_year_deltas" ("insee_code", "year", "base_year");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_apts_section_year_deltas" ON "apartments_by_section_year_deltas" ("section", "year", "base_year");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_houses_section_year_deltas" ON "houses_by_section_year_deltas" ("section", "year", "base_year");
